name: Latest YouTube Videos
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bitRAKE/youtube-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCkGGVSKvIZQlVqN4E1-Lp7w"